import { OperatorTools } from "@/components/OperatorTools";

export default function HomePage() {
  return (
    <main className="min-h-screen bg-slate-950 text-slate-50">
      <div className="mx-auto max-w-4xl px-4 py-10 space-y-10">
        {/* Hero */}
        <header className="space-y-4 pt-4">
          <p className="text-xs font-semibold uppercase tracking-[0.25em] text-slate-500">
            NightFrame
          </p>
          <h1 className="text-4xl font-black tracking-tight text-slate-50 sm:text-5xl">
            Built for the shift. Designed for results.
          </h1>
          <p className="max-w-xl text-sm text-slate-300 sm:text-base">
            You work nights, weekends, and holidays. NightFrame turns your real schedule into a
            weekly frame for training, sleep, and food that doesn&apos;t fight your job.
          </p>
          <div className="flex flex-wrap items-center gap-3">
            <a
              href="#intake"
              className="inline-flex items-center justify-center rounded-md bg-orange-500 px-5 py-2.5 text-sm font-semibold text-slate-950 shadow-sm hover:bg-orange-400 focus:outline-none focus:ring-2 focus:ring-orange-500"
            >
              Build my plan
            </a>
            <p className="text-xs text-slate-500">
              Built for ATC, cops, EMTs, nurses, and anyone living off the clock.
            </p>
          </div>
        </header>

        {/* 3-value props */}
        <section className="grid gap-4 pt-4 sm:grid-cols-3">
          <div className="rounded-md border border-slate-800 bg-slate-900/60 p-3">
            <p className="text-xs font-semibold uppercase tracking-wide text-orange-400">
              Shifts first
            </p>
            <p className="mt-1 text-xs text-slate-200">
              Workouts built around your actual hours, not a 9–5 fantasy.
            </p>
          </div>
          <div className="rounded-md border border-slate-800 bg-slate-900/60 p-3">
            <p className="text-xs font-semibold uppercase tracking-wide text-orange-400">
              Simple nutrition
            </p>
            <p className="mt-1 text-xs text-slate-200">
              Straight calorie + protein targets. No macro apps, no food guilt.
            </p>
          </div>
          <div className="rounded-md border border-slate-800 bg-slate-900/60 p-3">
            <p className="text-xs font-semibold uppercase tracking-wide text-orange-400">
              Chad-built plans
            </p>
            <p className="mt-1 text-xs text-slate-200">
              Your plan is generated by Chad, an AI coach tuned for shift life.
            </p>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">Who it&apos;s for</h2>
          <ul className="list-disc space-y-1 pl-5 text-slate-300">
            <li>Night-shift or rotating-shift workers (ATC, nurses, cops, EMTs, factory, logistics, etc.).</li>
            <li>People tired of generic 9–5 fitness advice that ignores their schedule.</li>
            <li>Anyone who wants a simple, repeatable weekly plan they can actually follow.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">What NightFrame does</h2>
          <ol className="list-decimal space-y-1 pl-5 text-slate-300">
            <li>You enter your work shifts and basic goals.</li>
            <li>NightFrame builds a weekly frame: when to sleep, when to train, and rough calorie/protein targets.</li>
            <li>You get a simple plan you can follow around your shifts.</li>
          </ol>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">Example week (fictional)</h2>
          <p className="text-slate-300">
            Example: 4 nights on (19:00–07:00), 3 off. NightFrame might suggest something like:
          </p>
          <div className="overflow-x-auto rounded-md border border-slate-800 bg-slate-900/60">
            <table className="w-full text-sm">
              <thead className="bg-slate-900/80 text-slate-300">
                <tr>
                  <th className="px-3 py-2 text-left">Day</th>
                  <th className="px-3 py-2 text-left">Sleep</th>
                  <th className="px-3 py-2 text-left">Training</th>
                  <th className="px-3 py-2 text-left">Food target</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-t border-slate-800">
                  <td className="px-3 py-2">Mon (on)</td>
                  <td className="px-3 py-2">08:00–14:00</td>
                  <td className="px-3 py-2">Light run before shift</td>
                  <td className="px-3 py-2">~1,800 kcal, 180–200g protein</td>
                </tr>
                <tr className="border-t border-slate-800">
                  <td className="px-3 py-2">Tue (on)</td>
                  <td className="px-3 py-2">08:30–14:30</td>
                  <td className="px-3 py-2">Rest</td>
                  <td className="px-3 py-2">~1,800 kcal, high protein, low junk</td>
                </tr>
                <tr className="border-t border-slate-800">
                  <td className="px-3 py-2">Wed (on)</td>
                  <td className="px-3 py-2">08:00–14:00</td>
                  <td className="px-3 py-2">Easy strength session after shift</td>
                  <td className="px-3 py-2">~1,900 kcal, focus on recovery</td>
                </tr>
                <tr className="border-t border-slate-800">
                  <td className="px-3 py-2">Thu (on)</td>
                  <td className="px-3 py-2">08:00–14:00</td>
                  <td className="px-3 py-2">Rest / mobility</td>
                  <td className="px-3 py-2">~1,700–1,800 kcal</td>
                </tr>
                <tr className="border-t border-slate-800">
                  <td className="px-3 py-2">Fri (off)</td>
                  <td className="px-3 py-2">Core sleep 03:00–09:00</td>
                  <td className="px-3 py-2">Longer run or lift</td>
                  <td className="px-3 py-2">~2,000 kcal, higher carbs</td>
                </tr>
              </tbody>
            </table>
          </div>
          <p className="text-xs text-slate-500">
            This is an example only. NightFrame will generate a plan around your actual shifts and goals.
          </p>
        </section>

        <section id="intake" className="space-y-4">
          <h2 className="text-xl font-semibold">Tell us about your shifts</h2>
          <p className="text-slate-300">
            NightFrame is in early beta. Fill this out with how you actually live. Chad will use it
            to build a weekly frame you can follow without wrecking your job or your sleep.
          </p>

          <form
            method="POST"
            action="/api/submit"
            className="space-y-4 rounded-md border border-slate-800 bg-slate-900/60 p-4"
          >
            {/* Schedule */}
            <div className="space-y-1">
              <label className="text-sm font-medium" htmlFor="shifts">Shift schedule / hours</label>
              <textarea
                id="shifts"
                name="shifts"
                required
                rows={2}
                placeholder="e.g. 4 nights on (19:00–07:00), 3 off, or 1 week 13:30–22:00 / 1 week 06:30–14:30"
                className="w-full rounded bg-slate-950 px-3 py-2 text-sm text-slate-50 border border-slate-700 focus:outline-none focus:ring-2 focus:ring-orange-500"
              />
            </div>

            {/* Training & goal */}
            <div className="grid gap-4 sm:grid-cols-3">
              <div className="space-y-1">
                <label className="text-sm font-medium" htmlFor="goal">Goal</label>
                <select
                  id="goal"
                  name="goal"
                  className="w-full rounded bg-slate-950 px-3 py-2 text-sm text-slate-50 border border-slate-700 focus:outline-none focus:ring-2 focus:ring-orange-500"
                >
                  <option value="lose">Lose fat</option>
                  <option value="maintain">Maintain</option>
                  <option value="gain">Build muscle</option>
                </select>
              </div>

              <div className="space-y-1">
                <label className="text-sm font-medium" htmlFor="trainingDays">Training days / week</label>
                <select
                  id="trainingDays"
                  name="trainingDays"
                  className="w-full rounded bg-slate-950 px-3 py-2 text-sm text-slate-50 border border-slate-700 focus:outline-none focus:ring-2 focus:ring-orange-500"
                >
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                  <option value="5">5+</option>
                </select>
              </div>

              <div className="space-y-1">
                <label className="text-sm font-medium" htmlFor="sessionLength">Session length (approx)</label>
                <input
                  id="sessionLength"
                  name="sessionLength"
                  type="text"
                  placeholder="e.g. 30–45 min"
                  className="w-full rounded bg-slate-950 px-3 py-2 text-sm text-slate-50 border border-slate-700 focus:outline-none focus:ring-2 focus:ring-orange-500"
                />
              </div>
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-1">
                <label className="text-sm font-medium" htmlFor="wantsToRun">Cardio preference</label>
                <select
                  id="wantsToRun"
                  name="wantsToRun"
                  className="w-full rounded bg-slate-950 px-3 py-2 text-sm text-slate-50 border border-slate-700 focus:outline-none focus:ring-2 focus:ring-orange-500"
                >
                  <option value="yes">I&apos;m fine with running</option>
                  <option value="no">No running – use incline walking</option>
                </select>
              </div>

              <div className="space-y-1">
                <label className="text-sm font-medium" htmlFor="runExperience">Running experience</label>
                <select
                  id="runExperience"
                  name="runExperience"
                  className="w-full rounded bg-slate-950 px-3 py-2 text-sm text-slate-50 border border-slate-700 focus:outline-none focus:ring-2 focus:ring-orange-500"
                >
                  <option value="beginner">Beginner</option>
                  <option value="intermediate">Intermediate</option>
                  <option value="advanced">Advanced</option>
                </select>
                <p className="text-xs text-slate-500">
                  If you choose no running, this just helps scale incline walking difficulty.
                </p>
              </div>
            </div>

            {/* You */}
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-1">
                <label className="text-sm font-medium" htmlFor="currentWeight">Current weight (lbs)</label>
                <input
                  id="currentWeight"
                  name="currentWeight"
                  type="number"
                  step="0.1"
                  className="w-full rounded bg-slate-950 px-3 py-2 text-sm text-slate-50 border border-slate-700 focus:outline-none focus:ring-2 focus:ring-orange-500"
                />
              </div>
              <div className="space-y-1">
                <label className="text-sm font-medium" htmlFor="targetWeight">Target weight (lbs)</label>
                <input
                  id="targetWeight"
                  name="targetWeight"
                  type="number"
                  step="0.1"
                  className="w-full rounded bg-slate-950 px-3 py-2 text-sm text-slate-50 border border-slate-700 focus:outline-none focus:ring-2 focus:ring-orange-500"
                />
              </div>
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-1">
                <label className="text-sm font-medium" htmlFor="jobType">Job type</label>
                <input
                  id="jobType"
                  name="jobType"
                  type="text"
                  placeholder="ATC, nurse, police, EMT, factory, etc."
                  className="w-full rounded bg-slate-950 px-3 py-2 text-sm text-slate-50 border border-slate-700 focus:outline-none focus:ring-2 focus:ring-orange-500"
                />
              </div>
              <div className="space-y-1">
                <label className="text-sm font-medium" htmlFor="email">Email</label>
                <input
                  id="email"
                  name="email"
                  type="email"
                  required
                  className="w-full rounded bg-slate-950 px-3 py-2 text-sm text-slate-50 border border-slate-700 focus:outline-none focus:ring-2 focus:ring-orange-500"
                />
              </div>
            </div>

            <div className="space-y-1">
              <label className="text-sm font-medium" htmlFor="constraints">Constraints / notes</label>
              <textarea
                id="constraints"
                name="constraints"
                rows={2}
                placeholder="Injuries, dietary constraints, preferred training times, anything else important."
                className="w-full rounded bg-slate-950 px-3 py-2 text-sm text-slate-50 border border-slate-700 focus:outline-none focus:ring-2 focus:ring-orange-500"
              />
            </div>

            <button
              type="submit"
              className="inline-flex items-center justify-center rounded bg-orange-500 px-4 py-2 text-sm font-semibold text-slate-950 hover:bg-orange-400 focus:outline-none focus:ring-2 focus:ring-orange-500"
            >
              Build my NightFrame
            </button>

            <p className="text-xs text-slate-500">
              In beta: plans are generated using your answers plus templates. You&apos;ll receive
              an email with your first weekly frame once it&apos;s ready.
            </p>
          </form>
        </section>
              <input
                id="email"
                name="email"
                type="email"
                required
                className="w-full rounded bg-slate-950 px-3 py-2 text-sm text-slate-50 border border-slate-700 focus:outline-none focus:ring-2 focus:ring-sky-500"
              />
            </div>

            <div className="space-y-1">
              <label className="text-sm font-medium" htmlFor="shifts">Shift pattern</label>
              <textarea
                id="shifts"
                name="shifts"
                required
                rows={2}
                placeholder="e.g. 4 nights on (19:00–07:00), 3 off"
                className="w-full rounded bg-slate-950 px-3 py-2 text-sm text-slate-50 border border-slate-700 focus:outline-none focus:ring-2 focus:ring-sky-500"
              />
            </div>

            <div className="space-y-1">
              <label className="text-sm font-medium" htmlFor="jobType">Job type</label>
              <input
                id="jobType"
                name="jobType"
                type="text"
                placeholder="ATC, nurse, police, EMT, factory, etc."
                className="w-full rounded bg-slate-950 px-3 py-2 text-sm text-slate-50 border border-slate-700 focus:outline-none focus:ring-2 focus:ring-sky-500"
              />
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-1">
                <label className="text-sm font-medium" htmlFor="goal">Goal</label>
                <select
                  id="goal"
                  name="goal"
                  className="w-full rounded bg-slate-950 px-3 py-2 text-sm text-slate-50 border border-slate-700 focus:outline-none focus:ring-2 focus:ring-sky-500"
                >
                  <option value="lose">Lose weight</option>
                  <option value="maintain">Maintain</option>
                  <option value="gain">Gain</option>
                </select>
              </div>

              <div className="space-y-1">
                <label className="text-sm font-medium" htmlFor="trainingDays">Training days per week</label>
                <select
                  id="trainingDays"
                  name="trainingDays"
                  className="w-full rounded bg-slate-950 px-3 py-2 text-sm text-slate-50 border border-slate-700 focus:outline-none focus:ring-2 focus:ring-sky-500"
                >
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                  <option value="5">5+</option>
                </select>
              </div>
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-1">
                <label className="text-sm font-medium" htmlFor="wantsToRun">Do you want to run?</label>
                <select
                  id="wantsToRun"
                  name="wantsToRun"
                  className="w-full rounded bg-slate-950 px-3 py-2 text-sm text-slate-50 border border-slate-700 focus:outline-none focus:ring-2 focus:ring-sky-500"
                >
                  <option value="yes">Yes, include running</option>
                  <option value="no">No, use incline walking instead</option>
                </select>
              </div>

              <div className="space-y-1">
                <label className="text-sm font-medium" htmlFor="runExperience">Running experience</label>
                <select
                  id="runExperience"
                  name="runExperience"
                  className="w-full rounded bg-slate-950 px-3 py-2 text-sm text-slate-50 border border-slate-700 focus:outline-none focus:ring-2 focus:ring-sky-500"
                >
                  <option value="beginner">Beginner</option>
                  <option value="intermediate">Intermediate</option>
                  <option value="advanced">Advanced</option>
                </select>
                <p className="text-xs text-slate-500">
                  If you choose "no" above, this is just used to scale incline walking difficulty.
                </p>
              </div>
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-1">
                <label className="text-sm font-medium" htmlFor="currentWeight">Current weight (lbs)</label>
                <input
                  id="currentWeight"
                  name="currentWeight"
                  type="number"
                  step="0.1"
                  className="w-full rounded bg-slate-950 px-3 py-2 text-sm text-slate-50 border border-slate-700 focus:outline-none focus:ring-2 focus:ring-sky-500"
                />
              </div>
              <div className="space-y-1">
                <label className="text-sm font-medium" htmlFor="targetWeight">Target weight (lbs)</label>
                <input
                  id="targetWeight"
                  name="targetWeight"
                  type="number"
                  step="0.1"
                  className="w-full rounded bg-slate-950 px-3 py-2 text-sm text-slate-50 border border-slate-700 focus:outline-none focus:ring-2 focus:ring-sky-500"
                />
              </div>
            </div>

            <div className="space-y-1">
              <label className="text-sm font-medium" htmlFor="constraints">Constraints / notes</label>
              <textarea
                id="constraints"
                name="constraints"
                rows={2}
                placeholder="Injuries, preferred training times, anything else important."
                className="w-full rounded bg-slate-950 px-3 py-2 text-sm text-slate-50 border border-slate-700 focus:outline-none focus:ring-2 focus:ring-sky-500"
              />
            </div>

            <button
              type="submit"
              className="inline-flex items-center justify-center rounded bg-sky-500 px-4 py-2 text-sm font-medium text-slate-950 hover:bg-sky-400 focus:outline-none focus:ring-2 focus:ring-sky-500"
            >
              Submit beta request
            </button>

            <p className="text-xs text-slate-500">
              In beta: plans are generated manually using your answers plus templates. You&apos;ll receive
              an email with your first weekly frame once it&apos;s ready.
            </p>
          </form>
        </section>

        {/* Chad intro */}
        <section className="space-y-3 rounded-md border border-slate-800 bg-slate-900/60 p-4">
          <h2 className="text-sm font-semibold text-slate-100">Who&apos;s Chad?</h2>
          <p className="text-xs text-slate-300">
            Chad is the AI coach behind NightFrame. He doesn&apos;t do influencer bullshit. He takes
            your shifts, your training time, your goal, and any constraints you give him and builds
            a weekly frame: full-body training, cardio that fits your joints and schedule, and
            simple nutrition numbers.
          </p>
        </section>

        {/* Operator section is a client component so we can use onClick handlers safely */}
        <OperatorTools />

        <footer className="pt-4 text-xs text-slate-600">
          NightFrame is for people who don&apos;t get normal weekends. No spam. No bullshit.
        </footer>
      </div>
    </main>
  );
}
